# Generated by Django 5.2 on 2025-04-18 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
